use serde::{Deserialize, Serialize};
use std::sync::Mutex;

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct AppSettings {
    // General
    pub clipboard_check_interval: u64,
    pub history_size: usize,
    pub launch_at_login: bool,
    pub paste_and_hide: bool,

    // Appearance
    pub popup_position: String,
    pub window_width: f64,
    pub window_height: f64,
    pub theme: String,
    pub preview_width: f64,

    // Ignore
    pub ignore_patterns: Vec<String>,
    pub ignored_apps: Vec<String>,
    pub ignored_types: Vec<String>,

    // Hotkeys
    pub global_hotkey: String,
    pub paste_hotkey: String,
}

impl Default for AppSettings {
    fn default() -> Self {
        Self {
            clipboard_check_interval: 500,
            history_size: 200,
            launch_at_login: false,
            paste_and_hide: true,

            popup_position: "cursor".to_string(),
            window_width: 400.0,
            window_height: 500.0,
            theme: "auto".to_string(),
            preview_width: 300.0,

            ignore_patterns: vec![],
            ignored_apps: vec![],
            ignored_types: vec![
                "org.nspasteboard.TransientType".to_string(),
                "org.nspasteboard.ConcealedType".to_string(),
                "org.nspasteboard.AutoGeneratedType".to_string(),
            ],

            global_hotkey: "Cmd+Shift+C".to_string(),
            paste_hotkey: "Cmd+Shift+V".to_string(),
        }
    }
}

pub struct SettingsManager {
    settings: Mutex<AppSettings>,
    config_path: std::path::PathBuf,
}

impl SettingsManager {
    pub fn new() -> Result<Self, String> {
        let home = dirs::home_dir().ok_or("Cannot find home directory")?;
        let config_dir = home.join(".maccy");
        std::fs::create_dir_all(&config_dir).map_err(|e| e.to_string())?;
        let config_path = config_dir.join("settings.json");

        let settings = if config_path.exists() {
            let content = std::fs::read_to_string(&config_path).map_err(|e| e.to_string())?;
            serde_json::from_str(&content).unwrap_or_default()
        } else {
            AppSettings::default()
        };

        Ok(Self {
            settings: Mutex::new(settings),
            config_path,
        })
    }

    pub fn get_settings(&self) -> AppSettings {
        self.settings.lock().unwrap().clone()
    }

    pub fn update_settings(&self, new_settings: AppSettings) -> Result<(), String> {
        let mut settings = self.settings.lock().unwrap();
        *settings = new_settings.clone();

        let json = serde_json::to_string_pretty(&new_settings).map_err(|e| e.to_string())?;
        std::fs::write(&self.config_path, json).map_err(|e| e.to_string())?;

        Ok(())
    }

    pub fn reset_to_default(&self) -> Result<(), String> {
        let default = AppSettings::default();
        self.update_settings(default)
    }
}
